# Generated by Django 4.2.2 on 2023-07-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groupOn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="group_id",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="user_id",
        ),
        migrations.AddField(
            model_name="messages",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groupOn.groupmembers",
            ),
        ),
    ]
