# Generated by Django 4.2.2 on 2023-07-14 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupOn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="message_id",
        ),
    ]
